version: "2.1"
networks:
  scot-net:
    driver: bridge

services:
  # command arguments are es-server port es-index indexfile start end date-parsetyp workers log-file
  esloaderfin_01:
    build: ./esloader_v3
    command: python3 esloader_finnews_mt2.py localhost 9200 fin_news ../anwar/finnews_dep_wft.txt 0 100000 fin 1 log.txt
    volumes:
      - /srv/data/anwar:/anwar
    networks:
      - scot-net
  
  esloader70m_01:
    build: ./esloader_v3
    command: python3 esloader_finnews_mt2.py localhost 9200 de70 ../anwar/de70mlcc_dep_wft.txt 0 1000000 de70 1 log.txt
    volumes:
      - /srv/data/anwar:/anwar
    networks:
      - scot-net

  